site_name: Victor Dinh
site_url: https://vd141.github.io
copyright: Copyright &copy; 2026 Victor Dinh
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Blog:
      - All Posts: blog/index.md
      - Tags: tags.md
  - Collections: collections.md
  - About: about.md
theme:
  name: material
  language: en
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.indexes
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: victor
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      accent: green
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      accent: green
  font:
    text: Gelasio
    code: Roboto Mono
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - blog:
  - tags
  - search
  - git-revision-date-localized:
      type: custom
      custom_format: "'last updated on' %b %d, %Y"  # Quote literal text for Babel pattern parsing
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vd141
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/victorhdinh
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/victor-dinh/
      name: LinkedIn
    - icon: material/rss
      link: /blog/
      name: Blog